namespace visland.Questing;
internal class Enums
{
    public enum ClassJob : uint
    {
        Adventurer = 0,
        Gladiator = 1,
        Pugilist = 2,
        Marauder = 3,
        Lancer = 4,
        Archer = 5,
        Conjurer = 6,
        Thaumaturge = 7,
        Carpenter = 8,
        Blacksmith = 9,
        Armorer = 10,
        Goldsmith = 11,
        Leatherworker = 12,
        Weaver = 13,
        Alchemist = 14,
        Culinarian = 15,
        Miner = 16,
        Botanist = 17,
        Fisher = 18,
        Paladin = 19,
        Monk = 20,
        Warrior = 21,
        Dragoon = 22,
        Bard = 23,
        Whitemage = 24,
        Blackmage = 25,
        Arcanist = 26,
        Summoner = 27,
        Scholar = 28,
        Rogue = 29,
        Ninja = 30,
        Machinist = 31,
        Darkknight = 32,
        Astrologian = 33,
        Samurai = 34,
        Redmage = 35,
        Bluemage = 36,
        Gunbreaker = 37,
        Dancer = 38,
        Reaper = 39,
        Sage = 40,
    }
}
